[package]
name = "cyberorganism"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = { version = "0.25.0", features = ["unstable-rendered-line-info"] }     # Terminal UI framework
crossterm = "0.27.0"   # Terminal manipulation
device_query = "1.1.3"  # Keyboard state monitoring
serde = { version = "1.0", features = ["derive"] }  # Serialization/Deserialization
serde_json = "1.0"     # JSON handling
chrono = { version = "0.4", features = ["serde"] }  # Date and time handling
unicode-segmentation = "1.10.1"  # Unicode grapheme handling
tui-input = "0.8.0"    # Text input handling with proper cursor support
fuzzy-matcher = "0.3.7"    # Fuzzy text matching

[dev-dependencies]
tempfile = "3.10.0"    # Temporary file handling for tests
