[package]
name = "cyberorganism"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = { version = "0.25.0", features = ["unstable-rendered-line-info"] }     # Terminal UI framework
crossterm = "0.27.0"   # Terminal manipulation
serde = { version = "1.0", features = ["derive"] }  # Serialization/Deserialization
serde_json = "1.0"     # JSON handling
chrono = { version = "0.4", features = ["serde"] }  # Date/time handling with serde support
